using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Roslynjector.Generator;

[Generator]
public sealed class RoslynjectorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext incrementalGeneratorInitializationContext)
    {
        var registrations = incrementalGeneratorInitializationContext.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node.IsAddCallCandidate(),
                static (context, _) => context.TransformAddCall()
            )
            .Where(static x => x is not null)!
            .Select(static (x, _) => x!)
            .Collect();
        
        incrementalGeneratorInitializationContext.RegisterSourceOutput(registrations, GenerateCode);
    }

    private static void GenerateCode(
        SourceProductionContext sourceProductionContext, 
        ImmutableArray<BindingInfoBase> bindingInfos)
    {
        var stringBuilder = new StringBuilder();
        stringBuilder.AppendLine("// <auto-generated/>");

        stringBuilder.AppendLine("public sealed class Container");
        stringBuilder.AppendLine("{");
        
        foreach (var bindingInfo in bindingInfos)
        {
            stringBuilder.AppendLine($"// {bindingInfo.Lifetime}");
            
            if (bindingInfo is FactoryBindingInfo factoryBindingInfo)
            {
                stringBuilder.AppendLine($"public {factoryBindingInfo.Service} {factoryBindingInfo.Service.ToString().Replace('.', '_')} => null; // factory({factoryBindingInfo.FactoryText});");
                continue;
            }
            
            if (bindingInfo is ImplementationBindingInfo implBindingInfo)
            {
                if (implBindingInfo.Implementation is not INamedTypeSymbol namedTypeSymbol) 
                    continue;

                var constructor = namedTypeSymbol.Constructors
                    .OrderByDescending(constructor => constructor.Parameters.Length)
                    .FirstOrDefault();
                
                if (constructor is null || constructor.Parameters.Length == 0)
                {
                    stringBuilder.AppendLine($"// {bindingInfo.Lifetime} = new {namedTypeSymbol}();");
                    continue;
                }
                
                stringBuilder.Append($"// {bindingInfo.Lifetime} = new {namedTypeSymbol}(");
                
                foreach (var parameterSymbol in constructor.Parameters)
                {
                    foreach (var attribute in parameterSymbol.GetAttributes())
                    {
                        stringBuilder.Append($"// [{attribute}] ");
                    }
                    
                    stringBuilder.AppendLine($"// {parameterSymbol}, ");
                }

                stringBuilder.AppendLine(");");
                continue;
            }

            stringBuilder.AppendLine($"//something went wrong with {bindingInfo}");
            stringBuilder.AppendLine();
        }
        
        stringBuilder.AppendLine("}");

        sourceProductionContext.AddSource("RegDump.g.cs", stringBuilder.ToString());
    }
}